// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.151.1.0.1.27  $
// File generated on 9/11/2002 8:28:17 AM from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\Documents and Settings\Ionel Munoz\My Documents\Visual Studio Projects\OpcClient\OPClient.tlb (1)
// LIBID: {DB3ACC27-9D70-4AC7-B944-42422B7F3DFF}
// LCID: 0
// Helpfile: 
// HelpString: OPClient Library
// DepndLst: 
//   (1) v2.0 stdole, (C:\WINDOWS\SYSTEM32\STDOLE2.TLB)
// ************************************************************************ //
#ifndef   OPClient_TLBH
#define   OPClient_TLBH

#pragma option push -b -w-inl

#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0600)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if defined(USING_ATLVCL) || defined(USING_ATL)
#if !defined(__TLB_NO_EVENT_WRAPPERS)
#include <atl/atlmod.h>
#endif
#endif


// *********************************************************************//
// Forward reference of some VCL types (to avoid including STDVCL.HPP)    
// *********************************************************************//
namespace Stdvcl {class IStrings; class IStringsDisp;}
using namespace Stdvcl;
typedef TComInterface<IStrings> IStringsPtr;
typedef TComInterface<IStringsDisp> IStringsDispPtr;

namespace Opclient_tlb
{

// *********************************************************************//
// HelpString: OPClient Library
// Version:    1.0
// *********************************************************************//


// *********************************************************************//
// GUIDS declared in the TypeLibrary. Following prefixes are used:        
//   Type Libraries     : LIBID_xxxx                                      
//   CoClasses          : CLSID_xxxx                                      
//   DISPInterfaces     : DIID_xxxx                                       
//   Non-DISP interfaces: IID_xxxx                                        
// *********************************************************************//
extern "C" const __declspec(selectany) GUID LIBID_OPClient = {0xDB3ACC27, 0x9D70, 0x4AC7,{ 0xB9, 0x44, 0x42,0x42, 0x2B, 0x7F,0x3D, 0xFF} };
};     // namespace Opclient_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Opclient_tlb;
#endif

#pragma option pop

#endif // OPClient_TLBH
